baseurl = "https://abraham.onl/"
title = "Abraham's Indieblog"
#themesDir = "/whiteplain/"
theme = "whiteplain"
languageCode = "ja"
# Disqus shortname
#disqusShortname = ""
# google analytics tracking id
googleAnalytics = "UA-112438396-18"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2018 Rajiv Abraham"

[params]
  # Date format
  #dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "Rajiv Abraham"

  # Gravatar or Abatar image
  gravatar = "a@brah.am"
  avatar = "/images/Abraham.jpg"

  twitter = "unoabraham"
  facebook = "939abraham"
  #googleplus = "Googleplus username"
  instagram = "unoabraham"
  tumblr = "unoabraham"
  flickr = "unoabraham"
  #reddit = "Reddit username"
  linkedin = "unoabraham"
  #slideshare = "Slideshare username"
  github = "unoabraham"
  #gitlab = "Gitlab username"
  #bitbucket = "Bitbucket username"
  #stackoverflow = "Stackoverflow username"
  #jsfiddle = "Jsfiddle username"
  #codepen = "Codepen username"
  #deviantart = "Deviantart username"
  #behance = "Behance username"
  #dribbble = "Dribbble username"
  #wordpress = "Wordpress username"
  #medium = "Medium username"
  foursquare = "unoabraham"
  #xing = "Xing username"
  #quora = "Quora username"
  #youtube = "Youtube username"
  #vimeo = "Vimeo username"
  #whatsapp = "Rajiv Abraham"
  #skype = "Skype username"
  #snapchat = "Snapchat username"
  #pinterest = "Pinterest username"
  #telegram = "Telegram username"
  #vine = "Vine username"
  email = "a@brah.am"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = 2
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "IndieWeb"
  weight = 3
  identifier = "indieweb"
  url = "/indieweb/"  
[[menu.main]]
  name = "Categories"
  weight = 4
  identifier = "categories"
  url = "/categories/"  
[[menu.main]]
  name = "Tags"
  weight = 5
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Archives"
  weight = 6
  identifier = "archives"
  url = "/archives/"


[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"